apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-app-set
spec:
  generators:
  - git:
      repoURL: https://github.com/Enferium/argo-applicationset-test.git
      revision: HEAD
      directories:
      - path: Chart/deploy/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Enferium/argo-applicationset-test.git
        targetRevision: HEAD
        path: 'Chart/'
        helm:
          valueFiles:
          - '../{{path}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{path.basename}}'
        namespace: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true