# domainName: customer1.colibrilent.ovh
# secrettls: customer1-colibrilent-ovh-tls
app:
  name: customer1-hello-world-k8s
  replicaCount: 1
image:
  repository: 67e29247.c1.gra9.container-registry.ovh.net/hello-k8s/hello-k8s
  tag: 1.0.2
service:
  port: 3000
ingress:
  host: customer1.circle-crm-dev.ovh
env:
  secrets:
    password: AgASSL107kpTHDm30b4uY3XgvnjhIzB8/EjN/g8Eizne3GDz8oeUPPhCATnorLgwpPQWbdWur+pylbWsak1WQuUVZaCZ6SG7P2PqoTIAlxGvq1hShJur4tLaNluNcIJ65PEuWhCH+QsS6g8dgvPQMAoda2t//mcZCXgumGBGsFBC2vB/uR0qMbAWUZ1dmcSeL5UuBUelNw/pC1ESyfPnR+wrtjhOI1jMCKrUA9jRSKh+LOeGQKDSZ3R1KfPup3auJbaFhJQb83Yknap0vA3iHvnm9nUbJKb0v9HLT9mB224QlFWaFJbq7iv9OhGFBtAoCG14x58G4qVoecTzKwIhqy9+v2R525sR+K16Sfva1Mupse6IgFTkP9uYbNZX6GfZ+Tvpxaa/K2bP9jKjipKPiRIrzRIdZjq8louPQLyQdg8ASzOpsn92xu9G2x1slca55KnzSafMySzud96DrjRAnd4bRcAQ6cIFGmhzFrEPPh3Y7ODNDx3tpmi24p8+D0B4kCYisR0HL4zK3LrjIux659BLhHmGk3zQJd1qseozccEG1VJcA41ESCGkrH0EF8KVfJZkTXE/9CGIoumZZFzpA1UKHG/0iJmEvYh8NT7tVbcChg4tBF+IgSkxXtVoV7ZqDsy13PM0Tz7890nCqpXz9dxS1xBbbYEiICUiOBUtW50cOWejPouMu9DaTCiyjY1LjhmSVpuj/S5Kg+Hg
    username: AgASSL107kpTHDm30b4uY3XgvnjhIzB8/EjN/g8Eizne3GDz8oeUPPhCATnorLgwpPQWbdWur+pylbWsak1WQuUVZaCZ6SG7P2PqoTIAlxGvq1hShJur4tLaNluNcIJ65PEuWhCH+QsS6g8dgvPQMAoda2t//mcZCXgumGBGsFBC2vB/uR0qMbAWUZ1dmcSeL5UuBUelNw/pC1ESyfPnR+wrtjhOI1jMCKrUA9jRSKh+LOeGQKDSZ3R1KfPup3auJbaFhJQb83Yknap0vA3iHvnm9nUbJKb0v9HLT9mB224QlFWaFJbq7iv9OhGFBtAoCG14x58G4qVoecTzKwIhqy9+v2R525sR+K16Sfva1Mupse6IgFTkP9uYbNZX6GfZ+Tvpxaa/K2bP9jKjipKPiRIrzRIdZjq8louPQLyQdg8ASzOpsn92xu9G2x1slca55KnzSafMySzud96DrjRAnd4bRcAQ6cIFGmhzFrEPPh3Y7ODNDx3tpmi24p8+D0B4kCYisR0HL4zK3LrjIux659BLhHmGk3zQJd1qseozccEG1VJcA41ESCGkrH0EF8KVfJZkTXE/9CGIoumZZFzpA1UKHG/0iJmEvYh8NT7tVbcChg4tBF+IgSkxXtVoV7ZqDsy13PM0Tz7890nCqpXz9dxS1xBbbYEiICUiOBUtW50cOWejPouMu9DaTCiyjY1LjhmSVpuj/S5Kg+Hg